version: '3'

services:

  mininet:
    build:
      context: .
    image: frndmg/mininet
    tty: true
    network_mode: "bridge"
    privileged: true
    environment:
     - DISPLAY
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     - /lib/modules:/lib/modules